name: Check RSAT matrix-clustering demos
on:
  push:

jobs:
  check-demos:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfontconfig1-dev libfribidi-dev

      # Step 3: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      # Step 4: Debug Cache Key
      - name: Debug Cache Key
        run: echo "Cache Key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}"

      # Step 5: Cache renv packages
      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # Step 6: Install renv
      - name: Install renv
        run: Rscript -e "install.packages(c('renv', 'svglite'))"

      # Step 7: Debug renv Library Path
      - name: Debug renv Library Path
        run: ls -R renv/library

      # Step 8: Restore R environment
      - name: Restore R environment
        run: Rscript -e "renv::restore()"

      # Step 9: Compile compare-matrices-quick
      - name: Compile compare-matrices
        run: |
          cd compare-matrices-quick
          make
          cd ..

      # Step 10: Run the demo script
      - name: Run Demo 1
        run: |
          Rscript matrix-clustering.R \
          -i data/OCT4_datasets/OCT4_motif_table.txt \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 1
