name: Check RSAT matrix-clustering demos
run-name: ${{ github.actor }}
on:
  push:
jobs:
  check-demos:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to access the files
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Install pak
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: pak
      
      - name: Install R packages
        run: |
          Rscript -e "pak::pkg_install(c(
            'dplyr', 'data.table', 'furrr', 'optparse', 'purrr', 
            'rcartocolor', 'reshape2', 'this.path', 'tidyr', 
            'dendsort', 'ggplot2', 'ggseqlogo', 'RColorBrewer', 
            'ape', 'RJSONIO', 'circlize', 'flexclust', 
            'htmlwidgets', 'plotly', 'svglite', 'jsonlite',
            'BiocManager'
          ))"
          Rscript -e "BiocManager::install(c('universalmotif', 'ComplexHeatmap'))"
      
      - name: Compile compare-matrices
        run: |
          cd compare-matrices-quick
          make
          cd ..
      
      - name: Run Demo 1
        run: |
          Rscript matrix-clustering.R \
          -i data/OCT4_datasets/OCT4_motif_table.txt \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 1