name: Check RSAT matrix-clustering demos
on:
  push:

jobs:
  check-demos:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install renv
      - name: Install renv
        run: Rscript -e "install.packages('renv')"

      # Step 4: Cache renv packages
      - name: Cache renv packages
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # Step 5: Restore R environment using renv
      - name: Restore R environment
        run: Rscript -e "renv::restore()"

      # Step 6: Compile compare-matrices-quick
      - name: Compile compare-matrices
        run: |
          cd compare-matrices-quick
          make
          cd ..

      # Step 7: Run the demo script
      - name: Run Demo 1
        run: |
          Rscript matrix-clustering.R \
          -i data/OCT4_datasets/OCT4_motif_table.txt \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 1
