name: Check RSAT matrix-clustering demos
run-name: ${{ github.actor }}

on:
  push:

jobs:
  check-demos:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repository to access the files
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::here 
            
            
      # Run the first demo
      - name: Demo 1
        run: |
          Rscript matrix-clustering.R                         \
          -i data/OCT4_datasets/OCT4_motif_table.txt          \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 8
