name: Check RSAT matrix-clustering demos
on:
  push:

jobs:
  check-demos:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Install non-R dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfontconfig1-dev libfribidi-dev
    
      # Step 3: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      # Step 4: Set RENV_PATHS_ROOT
      - name: Set RENV_PATHS_ROOT
        run: echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      # Step 5: Install and activate renv
      - name: Install renv and restore dependencies
        run: |
          Rscript -e "install.packages(c('renv', 'svglite'))"
          Rscript -e "renv::restore()"

      # Step 6: Cache renv packages
      - name: Cache Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # Step 7: Compile compare-matrices-quick
      - name: Compile compare-matrices
        run: |
          cd compare-matrices-quick
          make
          cd ..

      # --------- #
      # Run demos #
      # --------- #
      - name: Run Clustering Demo 1
        run: |
          Rscript matrix-clustering.R \
          -i data/OCT4_datasets/OCT4_motif_table.txt \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 1
          
      - name: Run Clustering Demo 2
        run: |
          Rscript matrix-clustering.R                         \
          -i data/JASPAR_2022/Jaspar_nematodes_motifs_tab.txt \
          -o results/JASPAR_nematodes_radial/JASPAR_nematodes \
          -a data/JASPAR_2022/JASPAR_nematodes_metadata.txt   \
          --radial_tree TRUE                                  \
          --title JASPAR_CORE_nematodes                       \
          -w 1

      - name: Run Format Conversion Demo 1
        run: |
          Rscript convert-matrix.R             \
          -i data/example/one_example_motif.tf \
          --from tf --to jaspar                \
          --output_file results/convert-matrix_examples/One_motif/One_motif.jaspar 

      - name: Run Format Conversion Demo 2
        run: |
          Rscript convert-matrix.R              \
          -i data/example/two_example_motifs.tf \
          --from tf --to jaspar                 \
          --output_file results/convert-matrix_examples/Two_motifs/Two_motifs.jaspar 
    
    
      # Each demo with 1 and >1 motifs
      # Demos for Logo
      # Demos for Format conversion
      # Demos for Trim
