name: Check RSAT matrix-clustering demos
on:
  push:

jobs:
  check-demos:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfontconfig1-dev libfribidi-dev
    
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Set RENV_PATHS_ROOT
        run: echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/renv
          key: Linux-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            Linux-renv-

      - name: Install renv and restore dependencies
        run: |
          Rscript -e "install.packages(c('renv'))"
          Rscript -e "renv::restore()"

      - name: Debug File Structure
        run: ls -R

      - name: Compile compare-matrices
        run: |
          cd compare-matrices-quick
          ls
          make
          cd ..

      - name: Clustering (interactive trees)
        run: |
          Rscript matrix-clustering.R \
          -i data/OCT4_datasets/OCT4_motif_table.txt \
          -o results/OCT4_motifs_clusters/OCT4_motif_analysis \
          -w 1
          
      - name: Clustering (radial tree)
        run: |
          Rscript matrix-clustering.R                         \
          -i data/JASPAR_2022/Jaspar_nematodes_motifs_tab.txt \
          -o results/JASPAR_nematodes_radial/JASPAR_nematodes \
          -a data/JASPAR_2022/JASPAR_nematodes_metadata.txt   \
          --radial_tree TRUE                                  \
          --title JASPAR_CORE_nematodes                       \
          -w 1

      - name: Motif format conversion (one motif)
        run: |
          Rscript convert-matrix.R             \
          -i data/example/one_example_motif.tf \
          --from tf --to jaspar                \
          --output_file results/convert-matrix_examples/One_motif/One_motif.jaspar
          
      - name: Motif format conversion (two motifs)
        run: |
          Rscript convert-matrix.R              \
          -i data/example/two_example_motifs.tf \
          --from tf --to jaspar                 \
          --output_file results/convert-matrix_examples/Two_motifs/Two_motifs.jaspar 

      - name: Export logo (one motif)
        run: |
          Rscript convert-matrix.R             \
          -i data/example/one_example_motif.tf \
          --from tf --to jaspar                \
          --logos TRUE                         \
          --output_file results/convert-matrix_examples/One_motif_Logos/One_motif.jaspar 

      - name: Export logos (two motifs)
        run: |
          Rscript convert-matrix.R              \
          -i data/example/two_example_motifs.tf \
          --from tf --to jaspar                 \
          --logos TRUE                          \
          --output_file results/convert-matrix_examples/Two_motifs_Logos/Two_motifs.jaspar

      - name: Trimming (one motif)
        run: |
          Rscript convert-matrix.R             \
          -i data/example/one_example_motif.tf \
          --from tf --to jaspar                \
          --logos TRUE --trim TRUE             \
          --output_file results/convert-matrix_examples/One_motif_Trim/One_motif.jaspar

      - name: Trimming (two motifs)
        run: |
          Rscript convert-matrix.R              \
          -i data/example/two_example_motifs.tf \
          --from tf --to jaspar                 \
          --logos TRUE --trim TRUE              \
          --output_file results/convert-matrix_examples/Two_motifs_Trim/Two_motifs.jaspar


      # Each demo with 1 and >1 motifs
      # Demos for Trim
